language: ruby

rvm:
  - 2.1.1
  - 2.0.0
  - 1.9.3

gemfile:
  - gemfiles/Gemfile.activerecord-4.0
  - gemfiles/Gemfile.activerecord-4.1

script: "echo 'DO IT' && bundle exec rake spec"

notifications:
  hipchat:
    rooms:
      secure: "lLUK7HuJzZiae6dSB35I/ZlTI8guiRteImGQBhj1DKe533HPGZQHnhwAdML2YY6nLzhfw1uaXHNgGDCLTkylHK2ChLROHZicoX6mCLPqspwkB2GCx4K+1neltReeOIIi5ZIg2fz6wAV9rdSSaIBpIUg1717nhbOCP3ouIf0j3X0="
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Build</a>/<a href="%{compare_url}">Changes</a>)'
    format: 'html'
